### PR TITLE
`global` typename is not a receiver

### PR DESCRIPTION
**Pull request by piranna**

### CODE REVIEW

**Comment by sindresorhus** [comment]
The code changes look good, but you need to revert some of the other changes.

**Comment by sindresorhus** [comment]
@piranna Friendly bump :)

**Comment by piranna** [comment]
Sorry, missed this. What changes would you like I revert? Probably the ones regarding naming and fork references... Anything else? :-)

**Comment by sindresorhus** [comment]
package.json and readme changes

**Pull request closed without merging**
