### PR TITLE
`global` typename is not a receiver

### PR DESCRIPTION
**Pull request by piranna**
Not sure if it's a matter of my use case of of recent Node.js versions (I'm using v9.11.1), but I was getting an incorrect `global` callsite. By ignoring it so it's picked the next one, it's working correctly.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Would you be able to include a test?

**Comment by piranna** [comment]
Sorry for not answering on time. I have just checked it, and the error is still happening, I'm using `caller-callsite` on https://github.com/piranna/unify-config and when using upstream version it gets the config field of `package.json` file from `unify-config` (that's where is there the function being called), but with my change, it correctly take the config from the package using it (that's where the caller function exists).

Not fully sure how to create a repro project or a test for this, being so hidden... any suggestion would be welcome. Maybe it could be related to being caller in a different project from callee? If so, a project using `unify-config` and trying to get the config from `package.json` file `config` field would show the issue... Maybe a simple project with almost empty files would do the job?

**Comment by piranna** [comment]
You can find the updated code at https://github.com/sindresorhus/caller-callsite/compare/master...piranna:master. As you can see, it only does an extra check that typename is not `global`.

**Comment by piranna** [comment]
It seems that this issue is happening when it's a function not exported on `module.exports`, in that case is being set to `null`.

**Comment by piranna** [comment]
Ok, I think I've found the problem... a lack of documentation.

I though (since 3 years ago...) that this code was returning just the file that was calling and actual function, but it's not exactly that: it's trying to return the original bottom file in your code that does that, and depth is going up in the stack (bottom-top), while I was thinking it was being the other way (top-bottom), returning the inmediate caller and depth going down the stack. Also on the examples it's being used arrow functions, and I think that's the reason why it's currently being checked the type name for `null`: `getTypeName()` returns the `this` object used in the callsite, where for internal Node.js modules it's always `null`, and this is also the reason why by using regular functions I needed to check for `global` too, since by using arrow functions `this` is being set to the current module object, and regular functions use `global` scope as `this` object by default. These values can be set in the code, so that's not a very good check, and it would be better to check that the filename start with `node:`, that's what currently is being done to identify Node.js internal modules. I've implemented this at https://github.com/piranna/caller-callsite, and also cleaned and optimized it, just only that I've also make it return the stack top-most site that I feels it's more intuitive, so not sure if that's the correct way to do it or if using the bottom-most is on purposse... Any comment? :-) Would you accept a PR, or should I publish it as an independent package since behaviour is top-botton? Maybe a PR explaining the actual behaviour?

**Comment by sindresorhus** [comment]
@piranna Sorry for the late reply. This got forgotten in a tab. You're right that the order is currently incorrect, see: https://github.com/sindresorhus/caller-callsite/issues/7 PR welcome to fix this.

**Comment by piranna** [comment]
> @piranna Sorry for the late reply. This got forgotten in a tab.

No problem, this also happens to me all the time.


> You're right that the order is currently incorrect, see: #7 PR welcome to fix this.

Not sure if a PR or a new repo, it totally change the behavior so it would be a major version... I could be able to do a PR from https://github.com/piranna/caller-callsite, but it's a full refactor. What should we do?

**Comment by sindresorhus** [comment]
What to do is really up to you. I'm happy to receive a PR with the refactor too.

**Comment by piranna** [comment]
https://github.com/sindresorhus/caller-callsite/pull/10

Here you have the PR for the refactor. Probably some things would need to be reviewed, changed or reverted, specially the ones regarding project names and links.

**Comment by piranna** [comment]
At least it's something to start working on :-)

**Pull request closed without merging**
